export const companies = [
  {
    id: 'dunkin',
    name: "Dunkin'",
    city: 'Cebu Area — Franchise',
    logo: '/assets/logos/dunkin_new_logo.png',
    logoAlt: "Dunkin' logo",
    desc: 'Franchise anchor. ~70 outlets across Cebu, Bohol, and Mindanao.',
  },
  {
    id: 'queen-city',
    name: 'The Queen City Food Chain, Inc.',
    city: 'Cebu',
    logo: '/assets/logos/queen_city_food_chain.png',
    logoAlt: 'Queen City Food Chain logo',
    hideOnError: true,
    desc: 'Operating entity for Dunkin\' in Cebu.',
  },
  {
    id: 'golden-era',
    name: 'Golden Era Food Chain, Inc.',
    city: 'Cagayan de Oro',
    logo: '/assets/logos/golden_era.png',
    logoAlt: 'Golden Era Food Chain logo',
    desc: 'Dunkin\' franchise operations in Cagayan de Oro.',
  },
  {
    id: 'oro-grande',
    name: 'Oro Grande Food Chain, Inc.',
    city: 'Iligan',
    logo: '/assets/logos/oro_grande.png',
    logoAlt: 'Oro Grande Food Chain logo',
    desc: 'Dunkin\' franchise operations in Iligan.',
  },
  {
    id: 'rio-grande',
    name: 'Rio Grande Food Chain, Inc.',
    city: 'Butuan',
    logo: '/assets/logos/rio_grande.png',
    logoAlt: 'Rio Grande Food Chain logo',
    desc: 'Dunkin\' franchise operations in Butuan.',
  },
  {
    id: 'montana-de-oro',
    name: 'Montana De Oro Food Chain, Inc.',
    city: 'Bukidnon',
    logo: '/assets/logos/montana_de_oro.png',
    logoAlt: 'Montana De Oro Food Chain logo',
    desc: 'Dunkin\' franchise operations in Bukidnon.',
  },
  {
    id: 'lincoln-trading',
    name: 'Lincoln Trading',
    city: 'Cebu',
    logo: '/assets/logos/licoln_trading.png',
    logoAlt: 'Lincoln Trading logo',
    desc: 'Internal supply and distribution support for the group.',
  },
  {
    id: 'jonies',
    name: 'Jonies Sizzlers + Roast',
    city: 'Cebu',
    logo: '/assets/logos/jonies.png',
    logoAlt: 'Jonies Sizzlers + Roast logo',
    desc: 'Filipino comfort food with international influence. Est. 2000. Now franchising.',
  },
  {
    id: 'mix-eat',
    name: 'Mix Eat by Jonies',
    city: 'Cebu',
    logo: '/assets/logos/mix_eat.png',
    logoAlt: 'Mix Eat by Jonies logo',
    desc: 'Fast-casual offshoot of Jonies. Premium, accessible.',
  },
  {
    id: 'dragon',
    name: 'Dragon Fireworks',
    city: 'Cebu',
    logo: '/assets/logos/dragon.png',
    logoAlt: 'Dragon Fireworks logo',
    desc: 'Pyrotechnics and events across Visayas-Mindanao.',
  },
  {
    id: 'linsy',
    name: 'Linsy Philippines Home Furniture',
    city: 'Cebu',
    logo: '/assets/logos/linsy.jpg',
    logoAlt: 'Linsy Philippines Home Furniture logo',
    desc: 'Home furniture retail and distribution.',
  },
  {
    id: 'grand-taishan',
    name: 'Grand Taishan Construction & Development Inc.',
    city: 'Cebu',
    logo: '/assets/logos/grand_taishan.png',
    logoAlt: 'Grand Taishan Construction logo',
    desc: 'General and restoration construction. Est. 2019.',
  },
  {
    id: 'gdc',
    name: 'Gesalem Hotel & Home Decor Inc.',
    city: 'Cebu',
    logo: '/assets/logos/gdc.png',
    logoAlt: 'Gesalem Hotel and Home Decor logo',
    hideOnError: true,
    desc: 'Interior design and home decor. Led by Janine Gesalem.',
  },
]

export const organizations = [
  {
    id: 'rotary',
    badge: 'President, RY 2012–2013',
    name: 'Rotary Club of Cebu',
    detail: 'District 3860 · Chartered 1932 · Cebu, Philippines',
    description:
      'Jonie served as President of the Rotary Club of Cebu during Rotary Year 2012-2013 under District 3860. Rotary is a global service organization whose members volunteer their time, resources, and expertise to tackle the world\'s most persistent challenges. His year of service reflects a long-standing commitment to community that runs parallel to his work in business.',
  },
  {
    id: 'yap-fraternity',
    badge: 'President',
    name: 'Yap Fraternity Cebu Inc.',
    detail: 'Est. Cebu Chapter 1970 · Golden 50th Anniversary 2025',
    description:
      'The Yap Fraternity is a socio-civic organization connecting the Yeh (Yap) clan across Cebu - not a college fraternity, but a family-bound community rooted in cultural preservation and mutual aid. Under Jonie\'s leadership, the fraternity has led disaster relief for fire victims in Barangay Tejero, distributed thousands of food packs for medical frontliners during the pandemic, and hosted traditional Chinese cultural celebrations including the Lions and Dragon Dance for Chinese New Year.',
  },
]
