export const companies = [
  {
    id: 'dunkin',
    name: "Dunkin'",
    city: 'Cebu Area — Franchise',
    logo: '/assets/logos/dunkin_new_logo.png',
    logoAlt: "Dunkin' logo",
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    carouselAssets: [
      { type: 'image', src: '/assets/carousell_assets/dunkin/dunkin_cebu_1.jpg' },
      { type: 'image', src: '/assets/carousell_assets/dunkin/dunkin_cebu_2.jpg' },
      { type: 'image', src: '/assets/carousell_assets/dunkin/dunkin_cebu_3.jpg' },
    ],
  },
  {
    id: 'queen-city',
    name: 'The Queen City Food Chain, Inc.',
    city: 'Cebu',
    logo: '/assets/logos/queen_city_food_chain.png',
    logoAlt: 'Queen City Food Chain logo',
    hideOnError: true,
    desc: 'Operating entity for Dunkin\' in Cebu.',
  },
  {
    id: 'golden-era',
    name: 'Golden Era Food Chain, Inc.',
    city: 'Cagayan de Oro',
    logo: '/assets/logos/golden_era.png',
    logoAlt: 'Golden Era Food Chain logo',
    desc: 'Dunkin\' franchise operations in Cagayan de Oro.',
  },
  {
    id: 'oro-grande',
    name: 'Oro Grande Food Chain, Inc.',
    city: 'Iligan',
    logo: '/assets/logos/oro_grande.png',
    logoAlt: 'Oro Grande Food Chain logo',
    desc: 'Dunkin\' franchise operations in Iligan.',
  },
  {
    id: 'rio-grande',
    name: 'Rio Grande Food Chain, Inc.',
    city: 'Butuan',
    logo: '/assets/logos/rio_grande.png',
    logoAlt: 'Rio Grande Food Chain logo',
    desc: 'Dunkin\' franchise operations in Butuan.',
  },
  {
    id: 'montana-de-oro',
    name: 'Montana De Oro Food Chain, Inc.',
    city: 'Bukidnon',
    logo: '/assets/logos/montana_de_oro.png',
    logoAlt: 'Montana De Oro Food Chain logo',
    desc: 'Dunkin\' franchise operations in Bukidnon.',
  },
  {
    id: 'lincoln-trading',
    name: 'Lincoln Trading',
    city: 'Cebu',
    logo: '/assets/logos/licoln_trading.png',
    logoAlt: 'Lincoln Trading logo',
    desc: 'Internal supply and distribution support for the group.',
  },
  {
    id: 'jonies',
    name: 'Jonies Sizzlers + Roast',
    city: 'Cebu',
    logo: '/assets/logos/jonies.png',
    logoAlt: 'Jonies Sizzlers + Roast logo',
    desc: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est, mauris placerat eleifend leo.',
    carouselAssets: [
      { type: 'image', src: '/assets/carousell_assets/jonies/jonies_cebu_1.jpg' },
      { type: 'image', src: '/assets/carousell_assets/jonies/jonies_2.jpg' },
      { type: 'image', src: '/assets/carousell_assets/jonies/jonies_3.jpg' },
    ],
  },
  {
    id: 'mix-eat',
    name: 'Mix Eat by Jonies',
    city: 'Cebu',
    logo: '/assets/logos/mix_eat.png',
    logoAlt: 'Mix Eat by Jonies logo',
    desc: 'Fast-casual offshoot of Jonies. Premium, accessible.',
  },
  {
    id: 'dragon',
    name: 'Dragon Fireworks',
    city: 'Cebu',
    logo: '/assets/logos/dragon.png',
    logoAlt: 'Dragon Fireworks logo',
    desc: 'Pyrotechnics and events across Visayas-Mindanao.',
  },
  {
    id: 'linsy',
    name: 'Linsy Philippines Home Furniture',
    city: 'Cebu',
    logo: '/assets/logos/linsy.jpg',
    logoAlt: 'Linsy Philippines Home Furniture logo',
    desc: 'Home furniture retail and distribution.',
  },
  {
    id: 'grand-taishan',
    name: 'Grand Taishan Construction & Development Inc.',
    city: 'Cebu',
    logo: '/assets/logos/grand_taishan.png',
    logoAlt: 'Grand Taishan Construction logo',
    desc: 'Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis.',
    carouselAssets: [
      { type: 'image', src: '/assets/carousell_assets/taishan/grand_taishan_jiann.avif' },
      { type: 'video', src: '/assets/carousell_assets/taishan/taishan_yukga.mp4' },
    ],
  },
  {
    id: 'gdc',
    name: 'Gesalem Hotel & Home Decor Inc.',
    city: 'Cebu',
    logo: '/assets/logos/gdc.png',
    logoAlt: 'Gesalem Hotel and Home Decor logo',
    hideOnError: true,
    desc: 'Interior design and home decor. Led by Janine Gesalem.',
  },
]

export const organizations = [
  {
    id: 'rotary',
    badge: 'President, RY 2012–2013',
    name: 'Rotary Club of Cebu',
    detail: 'District 3860 · Chartered 1932 · Cebu, Philippines',
    description:
      'Jonie served as President of the Rotary Club of Cebu during Rotary Year 2012-2013 under District 3860. Rotary is a global service organization whose members volunteer their time, resources, and expertise to tackle the world\'s most persistent challenges. His year of service reflects a long-standing commitment to community that runs parallel to his work in business.',
  },
  {
    id: 'yap-fraternity',
    badge: 'President',
    name: 'Yap Fraternity Cebu Inc.',
    detail: 'Est. Cebu Chapter 1970 · Golden 50th Anniversary 2025',
    description:
      'The Yap Fraternity is a socio-civic organization connecting the Yeh (Yap) clan across Cebu - not a college fraternity, but a family-bound community rooted in cultural preservation and mutual aid. Under Jonie\'s leadership, the fraternity has led disaster relief for fire victims in Barangay Tejero, distributed thousands of food packs for medical frontliners during the pandemic, and hosted traditional Chinese cultural celebrations including the Lions and Dragon Dance for Chinese New Year.',
  },
]
